### ISSUE TITLE
List of services

### ISSUE THREAD

**Issue by razbakov** [wehelplive/wehelp.live#33]
As a Refugee/Volunteer I want to see list of all services so that can find the best one for me. See Epic #7

Old version - https://wehelp.live/services

Design of card (see Figma):
<img width="503" alt="Screenshot 2022-04-25 at 22 23 53" src="https://user-images.githubusercontent.com/298778/165168834-2e7c1f7f-e267-41af-9847-780998a71953.png">

**Comment by amanuela97** [comment]
name - With right-justified second column
link - https://tailwindui.com/components/application-ui/lists/stacked-lists

**Comment by razbakov** [comment]
@amanuela97 I added design of card, can you please add this change to your PR?
